[package]
name = "kubo"
version = "0.1.0"
edition = "2021"
description = "Cliente de escritorio para Kubernetes — nativo, sin webview"

[dependencies]
eframe = { version = "0.35.0", default-features = false, features = ["accesskit", "default_fonts", "wgpu", "wayland", "x11"] }
egui = "0.35.0"
egui_extras = { version = "0.35.0", features = ["serde"] }
kube = { version = "4.2.0", features = ["client", "runtime", "ws", "derive", "rustls-tls", "socks5", "oidc"] }
k8s-openapi = { version = "0.28.0", features = ["latest"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "sync", "time", "io-util", "process", "net"] }
futures = "0.3.34"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_yaml_ng = "0.10.0"
anyhow = "1.0.104"
flume = "0.12.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
vt100 = "0.16.2"
base64 = "0.23.1"
png = "0.18.1"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = true

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"
